backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "public/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Теги", name: "tags", widget: "list", default: ["post"] }
      - { label: "Фото", name: "image", widget: "image" }
      - { label: "Подпись фото", name: "imageAlt", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }
